#!/usr/bin/env python3
"""
Compile Analysis Report

Combines all analysis files for a company into a single comprehensive report.

Usage:
    uv run python scripts/compile_report.py nota
    uv run python scripts/compile_report.py nota --output custom-report.md
"""

import argparse
import sys
from pathlib import Path
from datetime import date


def get_project_root() -> Path:
    """Get the project root directory."""
    return Path(__file__).parent.parent


def read_file_if_exists(filepath: Path) -> str | None:
    """Read file content if it exists, return None otherwise."""
    if filepath.exists():
        return filepath.read_text(encoding='utf-8')
    return None


def extract_section(content: str, start_marker: str = "---", skip_header: bool = True) -> str:
    """Extract content after the header section."""
    if not content:
        return ""

    lines = content.split('\n')

    if skip_header:
        # Skip everything before the first '---' after the header
        in_header = True
        dash_count = 0
        start_idx = 0

        for i, line in enumerate(lines):
            if line.strip() == '---':
                dash_count += 1
                if dash_count >= 2:  # After header section
                    start_idx = i + 1
                    break

        return '\n'.join(lines[start_idx:])

    return content


def compile_report(company: str, output_path: Path | None = None) -> str:
    """Compile all analysis files into a comprehensive report."""

    project_root = get_project_root()
    company_dir = project_root / "output" / company

    if not company_dir.exists():
        print(f"Error: Company directory not found: {company_dir}")
        sys.exit(1)

    # Read all analysis files
    files = {
        "summary": company_dir / "01-company-summary.md",
        "peers": company_dir / "02-peer-selection.md",
        "financials": company_dir / "03-financial-data.md",
        "valuation": company_dir / "04-valuation-analysis.md",
    }

    contents = {name: read_file_if_exists(path) for name, path in files.items()}

    # Check which files exist
    available = [name for name, content in contents.items() if content]
    missing = [name for name, content in contents.items() if not content]

    print(f"Available files: {', '.join(available)}")
    if missing:
        print(f"Missing files: {', '.join(missing)}")

    # Build report
    today = date.today().isoformat()

    report = f"""# {company.title()} Comparable Analysis Report

**회사:** {company.title()}
**분석일:** {today}
**분석가:** Claude AI
**버전:** v1.0

---

## Report Contents

This report compiles the following analysis:
"""

    for name in available:
        report += f"- {name.replace('_', ' ').title()}\n"

    report += "\n---\n\n"

    # Add each section
    if contents["summary"]:
        report += "## 1. 회사 개요\n\n"
        report += extract_section(contents["summary"])
        report += "\n---\n\n"

    if contents["peers"]:
        report += "## 2. Peer Group 분석\n\n"
        report += extract_section(contents["peers"])
        report += "\n---\n\n"

    if contents["financials"]:
        report += "## 3. 재무 데이터\n\n"
        report += extract_section(contents["financials"])
        report += "\n---\n\n"

    if contents["valuation"]:
        report += "## 4. 밸류에이션 분석\n\n"
        report += extract_section(contents["valuation"])
        report += "\n---\n\n"

    # Add footer
    report += f"""
---

**Disclaimer:** 본 분석은 교육 목적으로 작성되었으며, 투자 권유가 아닙니다.

---

Generated by compile_report.py | {today}
"""

    # Determine output path
    if output_path is None:
        reports_dir = project_root / "output" / "reports"
        reports_dir.mkdir(parents=True, exist_ok=True)
        output_path = reports_dir / f"{company}-comps-report-{today}.md"

    # Write report
    output_path.write_text(report, encoding='utf-8')
    print(f"\nReport compiled successfully: {output_path}")

    return str(output_path)


def main():
    parser = argparse.ArgumentParser(
        description="Compile analysis files into a comprehensive report"
    )
    parser.add_argument(
        "company",
        help="Company name (directory name in output/)"
    )
    parser.add_argument(
        "--output", "-o",
        type=Path,
        help="Custom output path for the report"
    )

    args = parser.parse_args()

    compile_report(args.company, args.output)


if __name__ == "__main__":
    main()
